feat: [sc-25580] Suggest next steps with old label-inspector repository
namehash/ens-label-inspector pull request #32
Opened 2024-10-31 21:41 UTC by Carbon225

Story details: https://app.shortcut.com/ps-web3/story/25580

2024-11-04 16:40 UTC, djstrong approved these changes

2024-11-04 16:41 UTC, djstrong requested changes
I think we need some information from the readme of ole inspector.

2024-11-25 08:15 UTC, lightwalker-eth approved these changes
@Carbon225 Nice work. Appreciate this. Thanks :+1:

2024-11-25 08:17 UTC, lightwalker-eth commented
@djstrong Nice work on maintainers readme :+1:

2024-11-25 08:18 UTC, merged